# Generated by Django 5.1.5 on 2025-12-01 22:26

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0017_alter_cheatingaudio_timestamp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheatingaudio',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 1, 22, 26, 14, 821716)),
        ),
        migrations.AlterField(
            model_name='cheatingevent',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 1, 22, 26, 14, 821440)),
        ),
        migrations.AlterField(
            model_name='cheatingimage',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 1, 22, 26, 14, 821595)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 1, 22, 26, 14, 821239)),
        ),
        migrations.AlterField(
            model_name='student',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 1, 22, 26, 14, 821011)),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(default=datetime.datetime(2025, 12, 1, 22, 26, 14, 821921))),
                ('file', models.ImageField(upload_to='certificates/')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='proctoring.exam')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='proctoring.student')),
            ],
        ),
    ]
