# Generated by Django 5.1.5 on 2025-12-01 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0018_alter_cheatingaudio_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='issued_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 1, 23, 2, 6, 286791)),
        ),
        migrations.AlterField(
            model_name='cheatingaudio',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 1, 23, 2, 6, 286591)),
        ),
        migrations.AlterField(
            model_name='cheatingevent',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 1, 23, 2, 6, 286311)),
        ),
        migrations.AlterField(
            model_name='cheatingimage',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 1, 23, 2, 6, 286466)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 1, 23, 2, 6, 286075)),
        ),
        migrations.AlterField(
            model_name='student',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 1, 23, 2, 6, 285794)),
        ),
    ]
