# Generated by Django 5.1.5 on 2025-12-02 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0020_alter_certificate_file_alter_certificate_issued_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='issued_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 2, 8, 21, 14, 99442)),
        ),
        migrations.AlterField(
            model_name='cheatingaudio',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 2, 8, 21, 14, 99223)),
        ),
        migrations.AlterField(
            model_name='cheatingevent',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 2, 8, 21, 14, 98914)),
        ),
        migrations.AlterField(
            model_name='cheatingimage',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 2, 8, 21, 14, 99089)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 2, 8, 21, 14, 98670)),
        ),
        migrations.AlterField(
            model_name='student',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 2, 8, 21, 14, 98370)),
        ),
    ]
