# Generated by Django 5.1.5 on 2025-12-02 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0022_alter_certificate_issued_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='issued_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 2, 16, 29, 42, 765239)),
        ),
        migrations.AlterField(
            model_name='cheatingaudio',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 2, 16, 29, 42, 765034)),
        ),
        migrations.AlterField(
            model_name='cheatingevent',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 2, 16, 29, 42, 764743)),
        ),
        migrations.AlterField(
            model_name='cheatingimage',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 2, 16, 29, 42, 764904)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 2, 16, 29, 42, 764528)),
        ),
        migrations.AlterField(
            model_name='student',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 2, 16, 29, 42, 764260)),
        ),
    ]
